story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("tugas1.urls")),
    path('',include("tugas4.urls")),
    path('admin/', admin.site.urls)
]

tugas1/urls.py
from django.urls import path, include
from .views import index
from django.contrib import admin

app_name = "tugas1"
urlpatterns=[
    
    path('',index,name='index')
]

tugas4/urls.py
from django.urls import path, include
from .views import contact,portofolio,form,savename,readperson,delete,detil,readhapus, formkegi, savekegi, Kegiatan, qna

app_name = "tugas4"
urlpatterns=[
    path('contact/',contact,name='contact'),
    path('portofolio/',portofolio,name='portofolio'),
    #path('matkul/',savename,name='savename')
    path('form/',form,name='form'),
    path('form/savename',savename),
    path('hasil/',readperson,name='hasil'),
    path('hasilhapus/',readhapus,name='hasilhapus'),
    path('hapus/<id>/',delete,name='delete'),
    path('detil/<id>/',detil,name='detil'),
    path('formkegiatan/',formkegi,name='formkegi'),
    path('formkegiatan/savekegi',savekegi),
    path('kegiatan/',Kegiatan),
    path('QNA/',qna, name ='QNA')
]

tugas1/models.py
from django.db import models

# Create your models here.

tugas4/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    #Person.objects.filter(id='sks').delete()
    name =models.CharField(max_length=200)
    dosen = models.CharField(max_length=200, default='')
    sks = models.IntegerField(blank=True, default=1)
    deskripsi = models.CharField(max_length=200, default='')
    semester = models.CharField(max_length=200, default='')
    ruangan = models.CharField(max_length=200, default='')
class Kegiatan(models.Model):
    namamu=  models.CharField(max_length=50, default='')
    kegiatan = models.CharField(max_length=50, default='')
    

tugas4/forms.py
from django import forms
from .models import Person,Kegiatan

CHOICES=[
    ('musik','musik'),('mabar','mabar'),("tidur","tidur"),
]

class Input_Form(forms.ModelForm):
    class Meta:
        model = Person  
        fields =['name','dosen','sks','deskripsi','semester','ruangan']
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'your name'

    }
    name = forms.CharField(label='Mata Kuliah:', required=True)
    dosen = forms.CharField(label='Nama Dosen:', required=True)
    sks = forms.IntegerField(label='SKS:', required=True, min_value=1, max_value=6)
    deskripsi = forms.CharField(required=False)
    semester = forms.CharField(label='Semester:', required=True)
    ruangan = forms.CharField(label='Ruang:', required=True, )


class dd_form(forms.ModelForm):
    namamu = forms.CharField(label='Nama:', required=True)
    kegiatan = forms.CharField(label='Kegiatan: ', widget=forms.Select(choices=CHOICES))
    class Meta:
        model = Kegiatan
        fields =['namamu','kegiatan']
    

tugas1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "index.html")

tugas4/views.py
from django.shortcuts import render
from .forms import Input_Form, CHOICES,dd_form 
from django.http import HttpResponseRedirect
from .models import Person,Kegiatan

# Create your views here.

def contact(request):
    return render(request,"contact.html")
def portofolio(request):
    return render(request,"portofolio.html")
def savename(request):
    form = Input_Form(request.POST or None)
    if(form.is_valid and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/form')
    else:
        return HttpResponseRedirect('/form')
def form(request):
    response={ 'input_form':Input_Form}
    return render(request,'form.html',response)

def readperson(request):
    objs=Person.objects.all()
    html = 'hasil.html'
    
    return render(request, html, {'objs':objs})

def readhapus(request):
    objs=Person.objects.all()
    html = 'hasilhapus.html'
    
    return render(request, html, {'objs':objs})

def delete(request,id):
    dele=Person.objects.get(id=id).delete()
    return render(request,'hapus.html',{'dele':dele,'Person':Person})

def detil(request,id):
    obj=Person.objects.get(id=id)
    
    return render(request,'detil.html',{'obj':obj,'Person':Person})

def formkegi(request):
    response={ 'dd_form':dd_form}
    return render(request,'formkegiatan.html',response)

def savekegi(request):
    form = dd_form(request.POST or None)
    if(form.is_valid and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/kegiatan')
    else:
        return HttpResponseRedirect('/kegiatan')
def Kegiatan(request,kegiatan):
    musik=Kegiatan.objects.get(kegiatan=="musik")
    mabar=Kegiatan.objects.get(kegiatan=="mabar")
    tidur=Kegiatan.objects.get(kegiatan=="tidur")
    
    return render(request,'kegiatan.html',{'musik':musik,'mabar':mabar,'tidur''Kegiatan':Kegiatan})

def qna(request):
    return render(request,"QNA.html")

tugas1/templates/index.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
    
    <div class="column-layout">
        <div class="left">
            <h1>Muhammad Irza</h1>
            <p><br><br>My name is Muhammad Irza.<br> I'm undergraduate student<br> of information system in Universitas Indonesia. <br>Looking forward for any opportunities <br>especially in IT and E-Sports.</p>
            <div class="btn">
                <a href="{% url 'tugas4:portofolio' %}">My Portofolio</a>
            </div>
        </div>    
        <div class="right">
            <div class="img">
                <img src="{% static 'untitled-removebg-preview (1).png' %}"style="width:276px;height:361px;position:relative;top:60px;left:100px" >
            </div>
        </div>
        
    </div>
    {% endblock %}

tugas4/templates/QNA.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Irza</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" type ="text/css" href="{% static 'style3.css' %}">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#accordion" ).accordion({
        header: "> div > h3",
        collapsible: true,
      active: false
        
      })
      .sortable({
        axis: "y",
        handle: "h3",
        stop: function( event, ui ) {
          // IE doesn't register the blur when sorting
          // so trigger focusout handlers to remove .ui-state-focus
          ui.item.children( "h3" ).triggerHandler( "focusout" );
 
          // Refresh accordion to handle new order
          $( this ).accordion( "refresh" );
        }
      });
  } );
  </script>
</head>
</head>
<body>
<h1 style="text-align: center;color: white;margin-top: 70px;">Q N A</h1>
<div id="accordion">
  <div class="group">
    <h3>Di mana kota kelahiranmu?</h3>
    <div class="acc">
      <img src="{% static 'sby.jpg' %}" class="img-fluid" style="width: 300px;height: 200px;">
      <p>Surabaya, kota pahlawan.</p>
    </div>
  </div>
  <div class="group">
    <h3>Apa Band Favoritmu?</h3>
    <div>
      <img src="{% static 'queen.png' %}" class="img-fluid" style="width: 300px;height: 200px;">
      <p style="margin-top: 40px;">One of the greatest rock band ever, Queen.</p>
    </div>
  </div>
  <div class="group">
    <h3>Siapa yang paling paling kau cintai?</h3>
    <div  class="acc"> 
    <img src="{% static 'fam1.jpg' %}" class="img-fluid" style="width: 200px;height: 300px;">
    <p>Keluarga. Tempat berangkat dan berpulang</p>
    </div>
  </div>
</div>
 
 
</body>
</html>

tugas4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type ="text/css" href="{% static 'style2.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block script %}
        
        {% endblock %}
    <title>Irza</title>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tugas1:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tugas4:portofolio' %}">Portofolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tugas4:contact' %}">Contact</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Form
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'tugas4:form' %}">Isi mata kuliah</a>
                <a class="dropdown-item" href="{% url 'tugas4:hasil' %}">Deskripsi Mata Kuliah</a>
                <a class="dropdown-item" href="{% url 'tugas4:hasilhapus' %}">Hapus mata kuliah</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
        {% block content %}
        
        {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>    
    </body>
</html>

tugas4/templates/contact.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
     
        
    <div class="subtitle"> 
        <h1>Contact me on</h1>
    </div>

    <ul class="a">
        <li style="color: #11a1bb ; "><a href="https://twitter.com/MuhIrza"><img src="{% static 'twit-removebg-preview.png' %}" width="90px" height="70px"></a> Twitter </li>
        <li style="color: #d824cf ;"><a href="https://www.instagram.com/muhammad_irza"><img src="{% static 'ig-removebg-preview.png' %}" width="70px" height="70px"></a>&nbsp; &nbsp; &nbsp; Instagram </li>
        <li style="color: #0251c9 ;"><a href="https://www.linkedin.com/in/muhammad-irza-830199186/"><img src="{% static 'linkeding-removebg-preview (2).png' %}" width="70px" height="70px"></a> &nbsp;&nbsp;&nbsp;    Linkedin </li>
        
    </ul>
    
    {% endblock %}

tugas4/templates/detil.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
     
    <table class="table" style="color: aliceblue;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Dosen</th>
            <th scope="col">SKS</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Semester</th>
            <th scope="col">Ruangan</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>{{obj.name}}</td>
            <td>{{obj.dosen}}</td>
            <td>{{obj.sks}}</td>
            <td>{{obj.deskripsi}}</td>
            <td>{{obj.semester}}</td>
            <td>{{obj.ruangan}}</td>
        </tbody>
      </table>
      <a class="btn btn-warning" href="{% url 'tugas4:form' %}" role="button" style="position: absolute;left: 630px; top: 400px">Kembali isi form</a>
    {% endblock %}

tugas4/templates/form.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}
    <h1 style="color: white; text-align: center;">Isi Mata Kuliah</h1>
        <form action="savename" method="POST" style=color:white>
                {% csrf_token %}
            <table class="tabel" style="margin-left: auto;margin-right: auto;">
                {{input_form.as_table}}
            </table>
            <input type="submit" value="Submit"> 
        </form>
    
        <a class="btn btn-warning" href="{% url 'tugas4:hasil' %}" role="button" style="position: absolute;left: 550px; top: 400px">Cek Deskripsi</a>
        <a class="btn btn-warning" href="{% url 'tugas4:hasilhapus' %}" role="button" style="position: absolute;left: 680px; top: 400px">Hapus Matkul</a>
    
    {% endblock %}

tugas4/templates/formkegiatan.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}
    <h1 style="color: white; text-align: center;">Yuk!</h1>
        <div class="row">
            <div class="col">
                <form action="savekegi" method="POST">
                    {% csrf_token %}
                    <table class="tabel" style="margin-left: auto;margin-right: auto;">
                        {{dd_form.as_table}}
                    </table>
                    <input type="submit" value="Submit"> 
            </div>
                    
                    
                </form>
                
        </div>
        
    
    {% endblock %}

tugas4/templates/hapus.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
     
           
   
        
       <h1 style="color: white; position:absolute ; left: 350px; top: 300px">Matkul yang dipilih berhasil dihapus!</h1>
       <a class="btn btn-warning" href="{% url 'tugas4:form' %}" role="button" style="position: absolute;left: 630px; top: 400px">Kembali isi form</a>
          
      
              
    {% endblock %}

tugas4/templates/hasil.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
     
  <h1 style="color: white; text-align: center;">Pilihlah Mata Kuliah yang ingin dilihat deskripsi</h1>      
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mata Kuliah
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for item in objs %}
          <a class="dropdown-item" href="{% url 'tugas4:detil' item.id%}">{{item.name}}</a>
          {% endfor %}
          
        </div>
      </div>
            
              
    {% endblock %}

tugas4/templates/hasilhapus.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
     
    <h1 style="color: white; text-align: center;">Pilihlah Mata Kuliah yang ingin dihapus</h1>     
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mata Kuliah
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for item in objs %}
          <a class="dropdown-item" href="{% url 'tugas4:delete' item.id%}">{{item.name}}</a>
          {% endfor %}
          
        </div>
      </div>
            
              
    {% endblock %}

tugas4/templates/kegiatan.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}
    <h1 style="color: white; text-align: center;">yuk ikut kegiatan!</h1>
    <div class="container">
        <div class="row">
          <div class="col">
            <h2 style="color: white; text-align: center;">Musik Sore</h2>
            <img src="{% static 'musik.jpg' %}" alt="Girl in a jacket" width="300" height="300">
            <h2 style="color: white; text-align: center;">Musik Sore</h2>
            {{musik.name}}
          </div>
          <div class="col">
            <h2 style="color: white; text-align: center;">Mabar!</h2>
            <img src="{% static 'mabar.jpg' %}" alt="Girl in a jacket" width="300" height="300">
            {{mabar.name}}
          </div>
          <div class="col">
            <h2 style="color: white; text-align: center;">Tidur</h2>
            <img src="{% static 'tidur.jpg' %}" alt="Girl in a jacket" width="300" height="300">
            {{tidur.name}}
          </div>
        </div>
      </div>
    {% endblock %}

tugas4/templates/portofolio.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
    

    <div class="subtitle"> 
        <h1>Portofolio</h1>
    </div>
    <div class="bg">
        <div class="column-layout">
            <div class="left">
                <p class="b">Praesent non nunc nunc. Fusce condimentum, arcu at pulvinar 
                    <br>maximus, dolor elit volutpat ipsum, et vulputate neque velit<br> non leo. 
                    In turpis mauris, condimentum quis ornare eu,<br> condimentum id turpis.
                    Proin euismod tincidunt hendrerit.<br> Aliquam vitae faucibus neque, sit amet sagittis nulla.
                    <br>Praesent non vehicula metus, non facilisis mauris.<br> Praesent ultrices sagittis ornare.
                    <br>Duis aliquam tortor vitae velit hendrerit, vitae vestibulum <br>mauris ultrices. 
                    Duis ultrices porta lacus in eleifend. </p>
                <p class="c">Praesent non nunc nunc. Fusce condimentum, arcu at pulvinar 
                    <br>maximus, dolor elit volutpat ipsum, et vulputate neque velit<br> non leo. 
                    In turpis mauris, condimentum quis ornare eu,<br> condimentum id turpis.
                    Proin euismod tincidunt hendrerit.<br> Aliquam vitae faucibus neque, sit amet sagittis nulla.
                    <br>Praesent non vehicula metus, non facilisis mauris.<br> Praesent ultrices sagittis ornare.
                    <br>Duis aliquam tortor vitae velit hendrerit, vitae vestibulum <br>mauris ultrices. 
                    Duis ultrices porta lacus in eleifend. </p>
                <p class="d">Praesent non nunc nunc. Fusce condimentum, arcu at pulvinar 
                    <br>maximus, dolor elit volutpat ipsum, et vulputate neque velit<br> non leo. 
                    In turpis mauris, condimentum quis ornare eu,<br> condimentum id turpis.
                    Proin euismod tincidunt hendrerit.<br> Aliquam vitae faucibus neque, sit amet sagittis nulla.
                    <br>Praesent non vehicula metus, non facilisis mauris.<br> Praesent ultrices sagittis ornare.
                    <br>Duis aliquam tortor vitae velit hendrerit, vitae vestibulum <br>mauris ultrices. 
                    Duis ultrices porta lacus in eleifend. </p>
                <p class="e">Praesent non nunc nunc. Fusce condimentum, arcu at pulvinar 
                    <br>maximus, dolor elit volutpat ipsum, et vulputate neque velit<br> non leo. 
                    In turpis mauris, condimentum quis ornare eu,<br> condimentum id turpis.
                    Proin euismod tincidunt hendrerit.<br> Aliquam vitae faucibus neque, sit amet sagittis nulla.
                    <br>Praesent non vehicula metus, non facilisis mauris.<br> Praesent ultrices sagittis ornare.
                    <br>Duis aliquam tortor vitae velit hendrerit, vitae vestibulum <br>mauris ultrices. 
                    Duis ultrices porta lacus in eleifend. </p>
            </div>    
            <div class="right">
                <div class="img">
                    <img src="{% static 'rsz_fifa.jpg' %}" style="position:relative;top:100px;left:10px;width:384px;height:216px;">
                    <img src="{% static 'rsz_pwc.jpg' %}" style="position:relative;top:180px;left:10px;width:384px;height:216px;">
                    <img src="{% static 'rsz_ps.jpg' %}" style="position:relative;top:260px;left:10px;width:384px;height:216px;">
                    <img src="{% static 'compfest.jpg' %}" style="position:relative;top:340px;left:10px;width:216px;height:216px;">
                </div>
            </div>
            
            
            
            
        </div>  
    </div>

    {% endblock %}